# Generated by Django 5.1.3 on 2024-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "Course_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("Course_name", models.CharField(max_length=128)),
                ("Teacher_name", models.CharField(max_length=128)),
            ],
        ),
    ]
